dependencies:
- name: rabbitmq
  repository: '@stable'
  version: ^6.1.1
  alias: rabbitmq
- name: postgresql
  repository: '@stable'
  version: ^5.3.10
  alias: postgres
- name: minio
  repository: '@stable'
  version: ^2.5.14
  alias: minio