# Endpoint Configuration
endpoints: {}

# Service level Configuration
config:
  converter:
    settings:
      # These directly map to handlebars configuration options
      video:
        codec: 'x264'
        profile: 'high'
        preset: 'veryfast'
        tune: 'animation'
        quality: 16
      audio:
        codec: 'copy:flac'
        fallback: 'flac16'
        mixdown: 'dpl2'
      subtitles:
        codec: 'copy'
        strip_pictures: true

# S3 Configuration
# Set the endpoint in endpoints.s3Endpoint
s3:
  accessKey: ''
  secretKey: ''

# Telegram Configuration
telegram:
  enabled: false
  # Telegram bot token
  token: ''
  # Channel to send new media notifications too
  channel: ''

# Trello Configuration
trello:
  enabled: false
  boardID: ''
  token: ''
  key: ''
  flow_ids:
    requests: ''
    ready: ''
    downloading: ''
    converting: ''
    uploading: ''
    deployed: ''
    errored: ''
  labels:
    metadata: ''
    error: ''
    movie: ''

# Infrastructure
rabbitmq:
  persistence:
    enabled: true
postgres:
  postgresqlDatabase: media
  postgresqlPassword: ''
  extraEnv:
  - name: ALLOW_EMPTY_PASSWORD
    value: "yes"
  persistence:
    enabled: true

# Service level manifest generation configuration
services:
  autoscaler:
    useServiceAccount: true

  beholder: {}

  converter:
    livenessProbe: false
    ports:
    - name: http
      containerPort: 3401
    volumes:
    - name: downloading
      emptyDir: {}
    - name: transcoding
      emptyDir: {}
    volumeMounts:
    - name: downloading
      mountPath: "/mnt/downloading"
    - name: transcoding
      mountPath: "/mnt/transcoding"

  downloader:
    livenessProbe: false
    ports:
    - name: http
      containerPort: 3401
    volumes:
    - name: downloading
      emptyDir: {}
    volumeMounts:
    - name: downloading
      mountPath: "/mnt/downloading"

  events:
    readinessProbePath: /v1/health
    livenessProbePath: /v1/health
    ports:
    - port: 80
      containerPort: 3401
      protocol: TCP
      name: webhook

  identifier:
    readinessProbe: false
    command: ["identifier"]

  twilight:
    readinessProbe: false
    livenessProbe: false
    ports:
    - name: http
      containerPort: 8001
      port: 80
      protocol: TCP
    command: ["twilight"]