{{- $name       := "centers" }}
{{- $fullname   := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $config     := index  .Values.services $name | default dict }}
{{- $jfConfig   := $config.jellyfin | default dict }}
{{- $plexConfig := $config.plex | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: service-configs
        persistentVolumeClaim:
          claimName: media-config
      - name: triton-config
        secret:
          defaultMode: 420
          secretName: media-config

      # Host mounts
      - name: media-v2
        hostPath: 
          path: /tmp/media-v2
          type: DirectoryOrCreate
      - name: fuse
        hostPath:
          path: /dev/fuse

      # Temp Dirs
      - name: transcoding
        emptyDir: {}
      containers:
{{include "includeJaegerContainer" . | indent 8 }}
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: {{ $plexConfig.imagePullPolicy }}
          env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: "999"
          - name: PGID
            value: "999"
          livenessProbe:
            httpGet:
              path: /
              port: 8096
              scheme: HTTP
            initialDelaySeconds: 60
          ports:
          - containerPort: 32400
            name: plex-http
            protocol: TCP
          - containerPort: 32400
            name: plex-http-udp
            protocol: UDP
          - containerPort: 32469
            protocol: TCP
          - containerPort: 32469
            protocol: UDP
          - containerPort: 5353
            protocol: UDP
          - containerPort: 1900
            protocol: UDP
          readinessProbe:
            httpGet:
              path: /
              port: 8096
              scheme: HTTP
          resources:
{{ toYaml $plexConfig.resources | indent 12 }}
          volumeMounts:
          - name: service-configs
            mountPath: /config
            subPath: plex
          - name: media-v2
            mountPath: /data
            mountPropagation: HostToContainer
          - name: transcoding
            mountPath: /transcoding
        # s3-mounter
        - name: s3-mounter
          image: jaredallard/triton-s3-mounter:v2
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            privileged: true
          env:
          - name: MOUNT_DIR
            value: /mnt/mdedia-v2/mnt
          - name: BUCKET_NAME
            value: triton-media
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: accesskey
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secretkey
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: endpoint
          volumeMounts:
          - name: fuse
            mountPath: /dev/fuse
          - name: media-v2
            mountPath: /mnt/media-v2
            mountPropagation: HostToContainer
            readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        # Jellyfin
        - name: jellyfin
          image: jellyfin/jellyfin:10.3.7
          imagePullPolicy: {{ $jfConfig.imagePullPolicy }}
          volumeMounts:
          - name: media-v2
            mountPath: /mnt/media-v2
            mountPropagation: HostToContainer
          - name: service-configs
            subPath: emby
            mountPath: /config
          ports:
          - name: http
            containerPort: 8096
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8096
            initialDelaySeconds: 60 # don't recreate until after 60s+
          readinessProbe:
            httpGet:
              path: /
              port: 8096
          resources:
{{ toYaml $jfConfig.resources | indent 12 }}
    {{- with $config.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
