{{- $name       := "jellyfin" }}
{{- $fullname   := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $config     := index  .Values.services $name | default dict }}
{{- $jfConfig   := $config.jellyfin | default dict }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ $jfConfig.serviceType }}
  ports:
  - port: {{ $jfConfig.servicePort | default 80 }}
    targetPort: 8096
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: centers
    app.kubernetes.io/instance: {{ .Release.Name }}
