{{- $name     := "events" }}
{{- $fullname := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $defaultImageRepository := printf "%s%s" "jaredallard/triton-" $name }}
{{- $config  := default (index (default .Values.config dict) $name) dict }}
apiVersion: v1
kind: Service
metadata:
  name: events
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3401
    protocol: TCP
    name: webhook
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with $config.serviceExternalIps }}
  externalIps:
{{ toYaml . | indent 4 }}
{{- end }}
