apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: autoscaler
rules:
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs: ["get", "list", "watch", "post", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoscaler
subjects:
  - kind: ServiceAccount
    name: autoscaler
    namespace: default
