{{- $name     := "twilight" }}
{{- $fullname := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $defaultImageRepository := "jaredallard/triton-twilight-go" }}
{{- $config  := default (index (default .Values.config dict) $name) dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: media-config
      containers:
        - name: {{ $name }}
          image: {{ $config.imageRepository | default $defaultImageRepository }}{{ ":" }}{{ $config.imageTag | default "prod" }}
          imagePullPolicy: {{ $config.imagePullPolicy }}
          command: ["twilight"]
          env:
          - name: NODE_ENV
            value: {{ $config.environment | default "production" }}
          - name: MINIO
            value: {{ .Values.global.s3Endpoint | default (printf "http://%s:9000" (include "service.fullname" (dict "Name" "minio" "Global" .))) }}
          - name: TWILIGHT_S3_ENDPOINT
            value: {{ include "service.fullname" (dict "Name" "rabbitmq" "Global" .) }}
          volumeMounts:
          - name: config
            mountPath: "/mnt/config"
            readOnly: true
          ports:
          - name: http
            containerPort: 8001
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60 # don't recreate until after 60s+
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
          resources:
            {{- toYaml $config.resources | nindent 12 }}
    {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
