{{- $name     := "twilight" }}
{{- $fullname := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $config  := default (index (default .Values.config dict) $name) dict }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ $config.serviceType }}
  ports:
    - port: {{ $config.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}