apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "downloader.fullname" . }}
  labels:
    app: {{ template "downloader.name" . }}
    chart: {{ template "downloader.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "downloader.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "downloader.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
{{include "includeJaegerContainer" . | indent 8 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
            - name: MINIO
              value: "http://gcs-proxy:9000"
          ports:
          - name: health
            containerPort: 3401
          volumeMounts:
            - name: config
              mountPath: "/mnt/config"
              readOnly: true
            - name: downloading
              mountPath: "/mnt/downloading"
            - name: transcoding
              mountPath: "/mnt/transcoding"
          readinessProbe:
            httpGet:
              path: /health
              port: 3401
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

      volumes:
        - name: config
          secret:
            secretName: media-config
        - name: downloading
          emptyDir: {}
        - name: transcoding
          emptyDir: {}
