{{- $global := . }}
{{- range $name, $serviceConfig := .Values.services }}
{{- $fullname := include "service.fullname" (dict "Name" $name "Global" $global) }}
{{- $defaultImageRepository := printf "%s%s" "jaredallard/triton-" ($serviceConfig.imageName | default $name) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ $global.Release.Service }}
    helm.sh/chart: {{ $global.Chart.Name }}{{ "-" }}{{ $global.Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $global.Release.Name }}
spec:
  replicas: {{ $serviceConfig.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $global.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ $global.Release.Name }}
    spec:
      {{- if eq (toString $serviceConfig.useServiceAccount) "true" }}
      serviceAccountName: {{ $fullname }}
      {{- end }}
      volumes:
      {{- include "triton.includeConfig" . | nindent 6 }}
      {{- with $serviceConfig.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $serviceConfig.imageRepository | default $defaultImageRepository }}{{ ":" }}{{ $serviceConfig.imageTag | default "prod" }}
          imagePullPolicy: {{ $serviceConfig.imagePullPolicy | default "IfNotPresent" }}
          {{- if eq (typeOf $serviceConfig.command) "[]interface {}" }}
          command: {{ $serviceConfig.command | toJson }}
          {{- else }}
          command: {{ default (list "/usr/bin/docker-entrypoint" $name) | toJson }}
          {{- end }}
          env:
          {{- $postgres := include "service.fullname" (dict "Name" "postgres" "Global" $global) }}
          {{- $rabbitmq := include "service.fullname" (dict "Name" "rabbitmq" "Global" $global) }}
          - name: NODE_ENV
            value: {{ $serviceConfig.environment | default "production" }}
          {{- if ne (toString $global.Values.trello.enabled) "true" }}
          - name: NO_TRELLO
            value: '1'
          {{- end }}
          {{- /* DEPRECATED */}}
          - name: POSTGRES
            value: {{ $postgres }}
          {{- /* DEPRECATED */}}
          - name: IDENTIFIER_POSTGRES_ENDPOINT
            value: {{ $postgres }}
          - name: POSTGRES_ENDPOINT
            value: {{ $postgres }}
          {{- /* DEPRECATED */}}
          - name: IDENTIFIER_RABBITMQ_ENDPOINT
            value: amqp://user:bitnami@{{ $rabbitmq }}
          - name: RABBITMQ
            value: amqp://user:bitnami@{{ $rabbitmq }}
          {{- /* DEPRECATED */}}
          - name: MINIO
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: endpoint
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: accesskey
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secretkey
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: endpoint
          {{- if (and (ne (toString $serviceConfig.livenessProbe) "false") (ne (len ($serviceConfig.ports | default list)) 0)) }}
          livenessProbe:
            httpGet:
              path: {{ $serviceConfig.livenessProbePath | default "/health" }}
              port: {{ $serviceConfig.livenessProbePort | default (index $serviceConfig.ports 0).containerPort }}
            initialDelaySeconds: 60 # don't recreate until after 60s+
          {{- end }}
          {{- if (and (ne (toString $serviceConfig.readinessProbe) "false") (ne (len ($serviceConfig.ports | default list)) 0)) }}
          readinessProbe:
            httpGet:
              path: {{ $serviceConfig.readinessProbePath | default "/health" }}
              port: {{ $serviceConfig.readinessProbePort | default (index $serviceConfig.ports 0).containerPort }}
          {{- end }}
          volumeMounts:
          {{- include "triton.includeConfigMount" . | nindent 10 }}
          {{- with $serviceConfig.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $serviceConfig.ports }}
          ports:
          {{- range $_, $port := . }}
          {{- /* TODO: Add more helpful error messages */}}
          - name: {{ $port.name | required "Missing port name"}}
            containerPort: {{ $port.containerPort | required "Missing containerPort" }}
            protocol: {{ $port.protocol | default "TCP" }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
    {{- with $serviceConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $serviceConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $serviceConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}