{{- $name     := "beholder" }}
{{- $fullname := include "service.fullname" (dict "Name" $name "Global" .) }}
{{- $defaultImageRepository := printf "%s%s" "jaredallard/triton-" $name }}
{{- $config  := default (index (default .Values.config dict) $name) dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}{{ "-" }}{{ .Chart.Version }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ $fullname }}
      volumes:
      - name: config
        secret:
          secretName: media-config
      containers:
{{ include "includeJaegerContainer" . | indent 6 }}
      - name: {{ $name }}
        image: {{ $config.imageRepository | default $defaultImageRepository }}{{ ":" }}{{ $config.imageTag | default "prod" }}
        imagePullPolicy: {{ $config.imagePullPolicy }}
        command: ["/usr/bin/docker-entrypoint", "{{ $name }}"]
        env:
        - name: POSTGRES
          value: {{ include "service.fullname" (dict "Name" "postgres" "Global" .) }}
        - name: NODE_ENV
          value: {{ $config.environment | default "production" }}
        volumeMounts:
        - name: config
          mountPath: "/mnt/config"
        resources:
{{ toYaml $config.resources | indent 10 }}
    {{- with $config.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
