apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: plex-http
    protocol: TCP
    name: http
  selector:
    app: media
    release: {{ .Release.Name }}
