apiVersion: extensions/v1beta1
kind: Ingress
{{- $endpoints := .Values.endpoints | default dict }}
metadata:
  name: services
  {{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | nindent 2 }}
  {{- end }}
spec:
  rules:
    - host: {{ $endpoints.events }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "events" "Global" .) }}
            servicePort: http
          path: /
    - host: {{ $endpoints.jellyfin }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "jellyfin" "Global" .) }}
            servicePort: http
          path: /
    - host: {{ $endpoints.plex }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "plex" "Global" .) }}
            servicePort: http
          path: /

{{- if eq (toString .Values.ingress.tlsEnabled) "true" }}
  tls:
  - hosts:
    - {{ $endpoints.events }}
    - {{ $endpoints.jellyfin }}
    - {{ $endpoints.plex }}
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}