apiVersion: extensions/v1beta1
kind: Ingress
{{- $endpoints := .Values.global.endpoints | default list }}
metadata:
  name: services
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $endpoints.events }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "events" "Global" .) }}
            servicePort: 80
          path: /
    - host: {{ $endpoints.media }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "jellyfin" "Global" .) }}
            servicePort: http
          path: /
    - host: {{ $endpoints.plex }}
      http:
        paths:
        - backend:
            serviceName: {{ include "service.fullname" (dict "Name" "plex" "Global" .) }}
            servicePort: http
          path: /
  tls:
  - hosts:
    - {{ $endpoints.events }}
    - {{ $endpoints.media }}
    - {{ $endpoints.plex }}
    secretName: app-tritonjs-com-tls
