{{- define "triton.generateConfig" }}
production:
  keys:
    # Trello configuration, a way to visually manage your media kinda.
    trello:
      token: {{ .trello.token }}
      key: {{ .trello.key }}

    # Telegram notifications
    telegram:
      token: {{ .telegram.token }}

    # S3 credentials
    minio:
      accessKey: {{ .s3.accessKey }}
      secretKey: {{ .s3.secretKey }}
  instances:
    # honestly idk
    default:
      host: '127.0.0.1'

    # Twilight Configuration
    media:
      # Used by Twilight in FS mode
      ## Base path for twilight to deploy into
      location: './production'
      types:
        # Deployment path for movies
        movie: '/movies'

        # Deployment path for tv
        tv: '/tv'

    # Converter Configuration
    converter:
      # Path read by downloader for that path to download into
      download_path: './downloading'

      # Path for converter to transcode in
      transcoding_path: './transcoding'

      # Encoder, only handbrake is supported at the moment
      encoder: 'handbrake'

      # See hanbrakejs options
      settings:
      {{- toYaml . | nindent 8 }}
    events:
      telegram:
        enabled: {{ .telegram.enabled }}
        channel: {{ .telegram.channel }}
      board: {{ .trello.boardID }}
      webhook: {{ .endpoints.events }}/webhook
      {{- with .trello.flow_ids }}
      flow_ids:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .trello.labels }}
      labels:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: media-config
  namespace: default
type: Opaque
data:
  config.yaml: {{ include "triton.generateConfig" .Values | b64enc }}