apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Opaque
data:
  accesskey: {{ .Values.s3.accessKey | b64enc }}
  secretkey: {{ .Values.s3.secretKey | b64enc }}
  endpoint: {{ .Values.endpoints.s3Endpoint | b64enc }}